controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

home:
    path: /joueur
    controller: App\Controller\CarteController::getMarkers

scan:
    path: /joueur/scan
    controller: App\Controller\JoueurController::scan

adv:
    path: /joueur/adv
    controller: App\Controller\JoueurController::adv

rank:
    path: /joueur/rank
    controller: App\Controller\JoueurController::rank

mission:
    path: /joueur/adv/mission
    controller: App\Controller\JoueurController::mission

setIsActuelle:
    path: joueur/set/aventure
    controller: App\Controller\JoueurController::setIsActuelle

concepteur_home:
    path: /concepteur
    controller: App\Controller\ConcepteurController::concepteur

concepteur_questions:
    path: /concepteur/questions
    controller : App\Controller\ConcepteurController::modif_question

concepteur_etapes:
    path: /concepteur/etapes
    controller : App\Controller\ConcepteurController::modif_etape

concepteur_aventure:
    path: /concepteur/aventure
    controller : App\Controller\ConcepteurController::creer_aventure
AdminMainPanel:
    path: /admin
    controller: App\Controller\AdminController::panel

manageRole:
    path: /admin/users/roles/{userid}
    controller: App\Controller\UserController::manageRole
    requirements:
        userid: '\d+'
    methods: 'POST'

roleError:
    path: /admin/error
    controller: App\Controller\AdminController::roleError

editUser:
    path: /admin/users/{userid}
    controller: App\Controller\UserController::editExistentUser
    requirements:
        userid: '\d+'

page_modification_aventure:
    path: /concepteur/modif_aventure
    controller: App\Controller\ConcepteurController::modif_aventure

page_ajout_etape_a_aventure:
    path: /concepteur/addEtape
    controller: App\Controller\ConcepteurController::addEtape

page_suppr_etape_a_aventure:
    path: /concepteur/delEtape
    controller: App\Controller\ConcepteurController::delEtape 

page_suppr_etape:
    path: /concepteur/delete_etape
    controller: App\Controller\ConcepteurController::deleteEtape    
    
page_suppr_aventure:
    path: /concepteur/delAventure
    controller: App\Controller\ConcepteurController::delAventure  

addUser:
    path: /admin/adduser
    controller: App\Controller\UserController::addUser

editEquipe:
    path: /admin/equipes/{equipeid}
    controller: App\Controller\EquipeController::editExistentEquipe
    requirements:
        userid: '\d+'

addEquiper:
    path: /admin/addEquipe
    controller: App\Controller\EquipeController::addEquipe

